Added examples for the common use cases when using the client
eclipse/ditto-clients-python pull request #10
Opened 2022-01-13 10:15 UTC by gabriela-yoncheva

- Modify/Create a feature in a thing (with a certain definition)
- Modify a feature's property
- Messages request-response handling flow

Signed-off-by: Gabriela Yoncheva <fixed-term.Gabriela.Yoncheva@bosch.io>

2022-01-13 10:19 UTC, gabriela-yoncheva commented
@thjaeckle Please do not merge this PR until it is approved by a member of the team.

2022-01-19 07:05 UTC, konstantina-gramatova requested changes

2022-01-19 07:05 UTC, konstantina-gramatova commented on examples/working_with_features.py
> +delete_feature_property(client)
All these commands must be performed after the client has notified it is conneced (i.e. in the on_connect hook). Currently, there is no guarantee that they will be executed properly. Please, fix it.


Another hint:
To keep the test representation "clean" - i.e. no changes after executing the example, maybe a better idea is to order the calls like - create/modify feature, create/modify a feature's propery, delete property, delete feature.

2022-01-19 07:05 UTC, konstantina-gramatova commented on examples/working_with_features.py
> +    command = Command(NamespacedID().from_string("test.ns:test-name")).feature("myFeatureID").twin().modify(myFeature)
It's a good practice to name the features in PascalCase. Please, fix it.

2022-01-19 07:05 UTC, konstantina-gramatova commented on examples/working_with_features.py
> +    myFeature = Feature().with_definition_from("my.model.namespace:FeatureModel:1.0.0").with_property("myProperty", "myValue")
Think about having the commonly used strings as private constants defined for the example - test namespaces/definition IDs, entity name, feature ID, etc.

2022-01-24 12:50 UTC, tinchouuu requested changes

2022-01-24 12:50 UTC, tinchouuu commented on examples/message_request_response_handling.py
> +    live_message_envelope = live_message.envelope(response_required=True)
Correlation ID is not set - please, add it.

2022-01-24 12:50 UTC, tinchouuu commented on examples/message_request_response_handling.py
> +    live_message = Message(thing_id).inbox(subject=message_subject).with_payload("some_payload")
Should be possible to use the short notation for the .inbox(message_subject) call here.

2022-01-24 12:53 UTC, konstantina-gramatova requested changes

2022-01-24 12:53 UTC, konstantina-gramatova commented on examples/message_request_response_handling.py
> +    live_message_envelope = live_message.envelope(response_required=True)
Correlation ID is missing - please, set it in the example.

2022-01-24 12:53 UTC, konstantina-gramatova commented on examples/message_request_response_handling.py
> +    live_message = Message(thing_id).inbox(subject=message_subject).with_payload("some_payload")
The short notation of the .inbox(message_subject) should be possible to be used as well.

2022-01-26 11:33 UTC, konstantina-gramatova approved these changes
LGTM

2022-01-26 12:35 UTC, merged