Created README.md file with code snippets for the main library functi…onalities.
eclipse/ditto-clients-python pull request #11
Opened 2022-01-27 10:14 UTC by ognian-baruh

Signed-off-by: Ognian Baruh <fixed-term.Ognyan.Baruh@bosch.io>

2022-01-27 10:15 UTC, ognian-baruh commented
@thjaeckle please don't merge this PR until a member of the team has approved it.

2022-01-31 08:10 UTC, konstantina-gramatova requested changes

2022-01-31 08:10 UTC, konstantina-gramatova commented on README.md
> +### Creating a client instance as a class
To keep the README crisp - this section (class implementation approach) could be just mentioned as a usage possibility with a reference to the full example but not as a whole section.

The key info in this example is actually the possibility to use an external Paho client.

2022-01-31 08:10 UTC, konstantina-gramatova commented on README.md
> +client.connect("localhost")
In difference to the Go library, the connection configurations here are provided per connection not per client instance, thus, would be nice to have an example for using them - e.g. connecting to a specific port, using a specific keep_alive, etc. In this sense, the whole section below (using as a class) can be narrowed down to a config option mention.

2022-01-31 08:10 UTC, konstantina-gramatova commented on README.md
> +        print("[{}] {}".format(level, string))
Could be narrowed down and included in the connection configuration options in the beginning.

2022-01-31 08:10 UTC, konstantina-gramatova commented on README.md
> +    paho_client.publish(topic=req_topic + message_subject, payload=live_message_json)
This is an example helper - please, leave it out.

2022-02-11 13:20 UTC, merged